libname bios591 "H:\BIOS591";
*descriptive statistics:;
proc contents data=bios591.fitness;
run;
proc univariate data=bios591.fitness;
var oxygen_consumption;
run;
proc univariate data=bios591.fitness;
var age;
run;
proc univariate data=bios591.fitness;
var weight;
run;
proc univariate data=bios591.fitness;
var runtime;
run;
proc univariate data=bios591.fitness;
var performance;
run;
*correlation analysis and checking assumption violations:;
proc corr data=bios591.fitness plots=matrix;
var age weight runtime performance;
with oxygen_consumption;
run;
*regression diagnostics:;
proc reg data=bios591.fitness;	*partial to produce partial plots, r and influence to create outlier diagnostics;
model oxygen_consumption=age weight runtime performance/ partial r influence;
run;
*re-run of regression:;
proc reg data=bios591.fitness simple; *simple produces means and SDs needed for table 1;
model oxygen_consumption=age weight runtime performance/partial r influence vif; *vif detects multicollinearity;
run;
*drop performance due to collinearity and re-run regression:;
proc reg data=bios591.fitness simple;
model oxygen_consumption=age weight runtime/partial r influence vif clb; *clb to produce 95% CI for regression parameters;
run;
*add 3 outlier detectors and see which observations they come from:;
ods graphics/imagemap=on;
proc reg data=bios591.fitness simple;
model oxygen_consumption=age weight runtime/partial r influence vif clb;
run;



libname bios591 "H:\BIOS591";
*descriptive statistics:;
proc contents data=bios591.fitness;
run;
proc univariate data=bios591.fitness;
var oxygen_consumption;
run;
proc univariate data=bios591.fitness;
var run_pulse;
run;
proc univariate data=bios591.fitness;
var rest_pulse;
run;
proc univariate data=bios591.fitness;
var maximum_pulse;
run;
*correlation analysis and checking assumption violations:;
proc corr data=bios591.fitness plots=matrix;
var run_pulse rest_pulse maximum_pulse;
with oxygen_consumption;
run;
*regression diagnostics:;
proc reg data=bios591.fitness;	*partial to produce partial plots, r and influence to create outlier diagnostics;
model oxygen_consumption=run_pulse rest_pulse maximum_pulse/ partial r influence;
run;
*re-run of regression:;
proc reg data=bios591.fitness simple; *simple produces means and SDs needed for table 1;
model oxygen_consumption=run_pulse rest_pulse maximum_pulse/partial r influence vif clb; *vif detects multicollinearity clb to produce 95% CI for regression parameters;
run;
*add 3 outlier detectors and see which observations they come from:;
ods graphics/imagemap=on;
proc reg data=bios591.fitness simple;
model oxygen_consumption=run_pulse rest_pulse maximum_pulse/partial r influence vif clb;
run;


