libname bios500 "H:\BIOS500";
*7a 95% CI: (5.69, 5.91);
proc means data=bios500.health n mean std stderr clm;
var wrist;
where sex=2;
run;
*7b 95% CI: (4.96, 5.17);
proc means data=bios500.health n mean std stderr clm;
var wrist;
where sex=1;
run;
*8;
proc freq data=bios500.nist;
tables marstat;
run;
*9;
data coverage;
seed=6041935; alpha=0.05; z=quantile ("norm",1-alpha/2);
p=0.01; n=1000;
do i = 1 to 10000;
x = ranbin(seed,n,p);
p_hat=x/n; n_tilde = n+4; p_tilde=(x+2)/n_tilde;
lower_w = p_hat - z*sqrt(p_hat*(1-p_hat)/n);
upper_w = p_hat + z*sqrt(p_hat*(1-p_hat)/n);
lower_a = p_tilde - z*sqrt(p_tilde*(1-p_tilde)/n_tilde);
upper_a = p_tilde + z*sqrt(p_tilde*(1-p_tilde)/n_tilde);
lower_s = p_hat*n/(n+z**2)+0.5*z**2/(n+z**2)-
z*sqrt(1/(n+z**2)*(p_hat*(1-p_hat)*n/(n+z**2)+.25*z**2/(n+z**2)));
upper_s = p_hat*n/(n+z**2)+0.5*z**2/(n+z**2)+
z*sqrt(1/(n+z**2)*(p_hat*(1-p_hat)*n/(n+z**2)+.25*z**2/(n+z**2)));
if lower_w <= p <= upper_w then captured_w = "yes";
else captured_w = "no";
if lower_a <= p <= upper_a then captured_a = "yes";
else captured_a = "no";
if lower_s <= p <= upper_s then captured_s = "yes";
else captured_s = "no";
output;
end;
keep lower_w upper_w lower_a upper_a lower_s upper_s captured_w captured_a captured_s;
run;
proc print data=coverage (obs=10);
run;
proc freq data=coverage;
tables captured_w captured_a captured_s;
run;
