data cigarette;
infile "H:\BIOS591\cigarette.dat";
input Brand$ Tar Nicotine Weight CO;
run;
proc contents data=cigarette;
run;
proc print data=cigarette;
run;
proc univariate data=cigarette;
var tar;
run;
proc univariate data=cigarette;
var co;
run;
proc univariate data=cigarette;
var weight;
run;
proc univariate data=cigarette;
var nicotine;
run;
proc reg;
model CO = Tar Nicotine Weight/partial;
run;
data corrected_cigarette;
set cigarette;
if tar = 6.6 then tar= 16.6;
run;
proc reg data=corrected_cigarette;
model co=tar nicotine weight/partial;
run;
