libname epi550 "H:\EPI550";
proc contents data=epi550.fham;
run;
*PART A;
*table 1: total baseline;
data total; 
set epi550.fham;
where period=1;
run;	*get total # of baseline observations;
proc univariate data=epi550.fham;
where period=1;
var age;
run;
proc univariate data=epi550.fham;
where period=1;
var bmi;
run;
proc freq data=epi550.fham;
tables CURSMOKE;
where period=1; *0=no 1=yes;
run;
proc freq data=epi550.fham;
tables sex; *1=male;
where period=1;
run;
proc freq data=epi550.fham;
tables educ;
where period=1;
run;
*1=0-11 years
2=High School Diploma, GED
3=Some College, Vocational School
4=College (BS, BA) degree or more;
proc freq data=epi550.fham;
tables death;
where period=1;
run;



*table 1: hypertension at baseline;
data hyperten; 
set epi550.fham;
where period=1 and hyperten=1;
run;	*get total # of baseline observations;
proc contents data=hyperten;
run;
proc univariate data=epi550.fham;
where period=1 and hyperten=1;
var age;
run;
proc univariate data=epi550.fham;
where period=1 and hyperten=1;
var bmi;
run;
proc freq data=epi550.fham;
tables CURSMOKE;
where period=1 and hyperten=1; *0=no 1=yes;
run;
proc freq data=epi550.fham;
tables sex; *1=male;
where period=1 and hyperten=1;
run;
proc freq data=epi550.fham;
tables educ;
where period=1 and hyperten=1;
run;
*1=0-11 years
2=High School Diploma, GED
3=Some College, Vocational School
4=College (BS, BA) degree or more;
proc freq data=epi550.fham;
tables death;
where period=1 and hyperten=1;
run;




*table 1: no hypertension at baseline;
data nohyperten; 
set epi550.fham;
where period=1 and hyperten=0;
run;	*get total # of baseline observations;
proc contents data=nohyperten;
run;
proc univariate data=epi550.fham;
where period=1 and hyperten=0;
var age;
run;
proc univariate data=epi550.fham;
where period=1 and hyperten=0;
var bmi;
run;
proc freq data=epi550.fham;
tables CURSMOKE;
where period=1 and hyperten=0; *0=no 1=yes;
run;
proc freq data=epi550.fham;
tables sex; *1=male;
where period=1 and hyperten=0;
run;
proc freq data=epi550.fham;
tables educ;
where period=1 and hyperten=0;
run;
*1=0-11 years
2=High School Diploma, GED
3=Some College, Vocational School
4=College (BS, BA) degree or more;
proc freq data=epi550.fham;
tables death;
where period=1 and hyperten=0;
run;


*PART B:
*age_bl;
*1 kaplan meier curves;
proc lifetest data=epi550.final;
time timedth*death(0);
strata hyperten_bl;
id randid;
run;
*log-rank test;
proc lifetest data=epi550.final;
time timedth*death(0);
strata hyperten_bl;
id randid;
run;

*PART C;
*PH assumption for age at baseline:;
*investigate age variable;
proc univariate data=epi550.final;
var age_bl;
where period=1;
run; *median=49;
*2 groups:;
*categorize into 2 groups: <=49 and >49;
data work1;
set epi550.final;
if age_bl <= 49 then age_cat = 1;
else age_cat = 2;
run;
*log-log survival curves;
proc lifetest data=work1 method=km plots=lls;
time timedth*death(0);
strata age_cat;
id randid;
run;
*3 groups:;
*categorize into 3 groups: ;
proc rank data=epi550.final out=ranked_age groups=3;
var age_bl;
ranks tertile;
where period=1;
run;
proc means data=ranked_age;
class tertile;
var age_bl;
run;
*3 groups: 32-44, 45-54, 55-70;
data work2;
set epi550.final;
if 32 <= age_bl <=44 then age_cat=0;
else if 45 <= age_bl <=54 then age_cat=1;
else if 55 <= age_bl <= 70 then age_cat=2;
run;
*log-log survival curves;
proc lifetest data=work2 method=km plots=lls;
time timedth*death(0);
strata age_cat;
run;
*goodness of fit;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=age_bl;
id randid;
assess ph / resample seed=550;
run;
*time-dep covariates;
*g(t)=t;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=age_bl age_bl_t;
age_bl_t=age_bl*timedth;
id randid;
run;
*g(t)=ln(t);
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=age_bl age_bl_lnt;
age_bl_lnt=age_bl*log(timedth);
id randid;
run;

*educ;
*log-log survival curves;
proc lifetest data=epi550.final method=km plots=lls;
time timedth*death(0);
strata educ;
id randid;
run;
*goodness of fit;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=educ;
id randid;
assess ph / resample seed=550;
run;
*time-dep covariates;
*g(t)=t;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=educ educ_t;
educ_t=educ*timedth;
id randid;
run;
*g(t)=ln(t);;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=educ educ_lnt;
educ_lnt=educ*log(timedth);
id randid;
run;

*hyperten_bl;
*log-log survival curves;
proc lifetest data=epi550.final method=km plots=lls;
time timedth*death(0);
strata hyperten_bl;
id randid;
run;
*goodness of fit;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=hyperten_bl;
id randid;
assess ph / resample seed=550;
run;
*time-dep covariates;
*g(t)=t;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=hyperten_bl hyperten_bl_t;
hyperten_bl_t=hyperten_bl*timedth;
id randid;
run;
*g(t)=ln(t);;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=hyperten_bl hyperten_bl_lnt;
hyperten_bl_lnt=hyperten_bl*log(timedth);
id randid;
run;

*sex;
*log-log survival curves;
proc lifetest data=epi550.final method=km plots=lls;
time timedth*death(0);
strata sex;
id randid;
run;
*goodness of fit;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=sex;
id randid;
assess ph / resample seed=550;
run;
*time-dep covariates;
*g(t)=t;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=sex sex_t;
sex_t=sex*timedth;
id randid;
run;
*g(t)=ln(t);;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=sex sex_lnt;
sex_lnt=sex*log(timedth);
id randid;
run;


*PART D;
*model D;
proc phreg data=epi550.final covs(aggregate) covm;
model timedth*death(0)=age_bl bmi cursmoke hyperten_bl_gt1 hyperten_bl_gt2 hyperten_bl_gt3 hyperten_bl_gt4;
strata sex educ;
gt1=0;
gt2=0;
gt3=0;
gt4=0;
if timedth ge 0 and timedth lt 2000 then gt1=1;
if timedth ge 2000 and timedth lt 4000 then gt2=1;
if timedth ge 4000 and timedth lt 6000 then gt3=1;
if timedth ge 6000 then gt4=1;
hyperten_bl_gt1=hyperten_bl*gt1;
hyperten_bl_gt2=hyperten_bl*gt2;
hyperten_bl_gt3=hyperten_bl*gt3;
hyperten_bl_gt4=hyperten_bl*gt4;
id RANDID; 
contrast "HR 0-1999 days" hyperten_bl_gt1 1 / estimate=exp;
contrast "HR 2000-3999 days" hyperten_bl_gt2 1 / estimate=exp;
contrast "HR 4000-5999 days" hyperten_bl_gt3 1 / estimate=exp;
contrast "HR 6000+ days" hyperten_bl_gt4 1 / estimate=exp;
run;



*PART E;
*1 unconditional logistic regression;
proc logisitic data=epi550.final;
where period=1;
model death (event="0") = hyperten_bl bmi age sex educ cursmoke;
run;
*other approach that gets same answers;
proc genmod data=epi550.final;
where period=1;
model death (event="0")= hyperten_bl bmi age sex educ cursmoke / dist=bin link=logit;
estimate "ROR for Effect of hyperten_bl" hyperten_bl 1/ exp;
run;
*2 poisson regression;
proc genmod data=epi550.final;
class randid;
model death = hyperten_bl bmi age sex educ cursmoke / dist=poisson link=log;
repeated subject = randid / type = unstr; 
where PERIOD = 1;
run;


*PART F;
*1 using contrast statemetns to get HR nd CIs;
proc phreg data=epi550.final covs(aggregate) covm;
model timechd*anychd(0)=bmiow bmiob cursmoke bmiow*sex bmiob*sex cursmoke*sex/rl;
id randid;
where PREVCHD = 0 and bmi ne .;
strata sex;
bmiow=0;
bmiob=0;
if bmi ge 25 and bmi lt 30 then bmiow=1;
if bmi ge 30 then bmiob=1;
contrast "HR for over weight males" bmiow 1 bmiow*sex 1 / estimate=exp;
contrast "HR for over weight females" bmiow 1 bmiow*sex 2 / estimate=exp; 
contrast "HR for obese males" bmiob 1 bmiob*sex 1 / estimate=exp;
contrast "HR for obese females" bmiob 1 bmiob*sex 2 / estimate=exp;
run;
*2 LRT;
*full model;
proc phreg data=epi550.final covs(aggregate) covm;
model timechd*anychd(0)=bmiow bmiob cursmoke sex bmiow*sex bmiob*sex/rl;
id randid;
where PREVCHD = 0 and bmi ne .;
bmiow=0;
bmiob=0;
if bmi ge 25 and bmi lt 30 then bmiow=1;
if bmi ge 30 then bmiob=1;
run;
*reduced model;
proc phreg data=epi550.final covs(aggregate) covm;
model timechd*anychd(0)=bmiow bmiob cursmoke sex/rl;
id randid;
where prevchd=0 and bmi ne .;
bmiow=0;
bmiob=0;
if bmi ge 25 and bmi lt 30 then bmiow=1;
if bmi ge 30 then bmiob=1;
run;
data LRT;
p=1-probchi(41446.311-41439.631, 2);
run;
proc print data=LRT;
run;
*3;
*adjusted model;
proc phreg data=epi550.final covs(aggregate) covm;
model timechd*anychd(0)=bmiow bmiob cursmoke sex bmiow*sex bmiob*sex/rl;
id randid;
where PREVCHD = 0 and bmi ne .;
bmiow=0;
bmiob=0;
if bmi ge 25 and bmi lt 30 then bmiow=1;
if bmi ge 30 then bmiob=1;
contrast "HR for over weight males" bmiow 1 bmiow*sex 1 / estimate=exp;
contrast "HR for over weight females" bmiow 1 bmiow*sex 2 / estimate=exp; 
contrast "HR for obese males" bmiob 1 bmiob*sex 1 / estimate=exp;
contrast "HR for obese females" bmiob 1 bmiob*sex 2 / estimate=exp;
run;
*crude model;
proc phreg data=epi550.final covs(aggregate) covm;
model timechd*anychd(0)=bmiow bmiob sex bmiow*sex bmiob*sex /rl;
id randid;
where PREVCHD = 0 and bmi ne .;
bmiow=0;
bmiob=0;
if bmi ge 25 and bmi lt 30 then bmiow=1;
if bmi ge 30 then bmiob=1;
contrast "HR for over weight males" bmiow 1 bmiow*sex 1 / estimate=exp;
contrast "HR for over weight females" bmiow 1 bmiow*sex 2 / estimate=exp; 
contrast "HR for obese males" bmiob 1 bmiob*sex 1 / estimate=exp;
contrast "HR for obese females" bmiob 1 bmiob*sex 2 / estimate=exp;
run;
