libname epi550 "H:\EPI550";
proc contents data=epi550.dhs_water;
*4;
proc logistic data = epi550.dhs_water;
model Breastfeeding(event = '1') = WaterDistance WaterSource;
run;
*5;
*full model;
proc logistic data = epi550.dhs_water;
model Breastfeeding(event = '1') = WaterDistance WaterSource;
run;
*reduced model;
proc logistic data = epi550.dhs_water;
where WaterDistance NE .;
model Breastfeeding(event = '1') = WaterSource;
run;
data pvalue;
p_value= 1-probchi(6.314,1);
run;
proc print data=pvalue;
run;

*7;
data epi550.dhs_water;
set epi550.dhs_water;
if WaterDistance = 0 then WaterDistance = -1;
run;
proc logistic data = epi550.dhs_water;
model Breastfeeding(event = '1') = WaterDistance WaterSource;
run;
