libname epi550 "H:\EPI550";
proc contents data=epi550.stillbirth;
run;
proc freq data=epi550.stillbirth;
tables state;
run;
*offset;
data epi550.stillbirth;
set epi550.stillbirth;
ln_deliveries = log(deliveries);
run;
*2;
proc genmod data = epi550.stillbirth;
model stillbirths = medicaid / link = log dist = poisson offset = ln_deliveries;
estimate 'IDR for Medicaid' medicaid 1;
run;
*3;
proc genmod data = epi550.stillbirth;
model stillbirths = fp_Q2 fp_Q3 fp_Q4 / link = log dist = poisson offset = ln_deliveries;
estimate 'IDR Q2 vs Q1'  fp_Q2 1;
estimate 'IDR Q3 vs Q1'  fp_Q3 1;
estimate 'IDR Q4 vs Q1'  fp_Q4 1;
run;
*5;
proc genmod data = epi550.stillbirth;
model stillbirths = medicaid fp_Q2 fp_Q3 fp_Q4
medicaid*fp_Q2 medicaid*fp_Q3 medicaid*fp_Q4 / link = log dist = poisson offset = ln_deliveries;
estimate "IDR medicaid fpQ1" medicaid 1;
estimate "IDR medicaid fpQ2" medicaid 1 medicaid*fp_Q2 1;
estimate "IDR medicaid fpQ3" medicaid 1 medicaid*fp_Q3 1;
estimate "IDR medicaid fpQ4" medicaid 1 medicaid*fp_Q4 1;
run;
*6:
*full model;
proc genmod data = epi550.stillbirth;
model stillbirths = medicaid fp_Q2 fp_Q3 fp_Q4
medicaid*fp_Q2 medicaid*fp_Q3 medicaid*fp_Q4 / link = log dist = poisson offset = ln_deliveries;
estimate "IDR medicaid fpQ1" medicaid 1;
estimate "IDR medicaid fpQ2" medicaid 1 medicaid*fp_Q2 1;
estimate "IDR medicaid fpQ3" medicaid 1 medicaid*fp_Q3 1;
estimate "IDR medicaid fpQ4" medicaid 1 medicaid*fp_Q4 1;
run; *Deviance of full model: 608.8479;
*reduced model;
proc genmod data = epi550.stillbirth;
model stillbirths = medicaid fp_Q2 fp_Q3 fp_Q4 / link = log dist = poisson offset = ln_deliveries;
run; *Deviance of reduced model: 770.5881;
*LRT for interaction;
data one;
p=1-probchi(161,74, 3);
put p;
run;
