libname epi550 "H:\EPI550";
proc contents data=epi550.nhanes_htn;
run;
*2;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR RIAGENDR AvgAlc*RIAGENDR;
run;
*3a 2 vs 0;
*females;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR RIAGENDR AvgAlc*RIAGENDR;
contrast "OR - AvgAlc - RIAGENDR = 0" AvgAlc 2 AvgAlc*RIAGENDR 4 / est=exp;
run;
*males;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR RIAGENDR AvgAlc*RIAGENDR;
contrast "OR - AvgAlc - RIAGENDR = 0" AvgAlc 2 AvgAlc*RIAGENDR 2 / est=exp;
run;
*3b 5 v 0;
*females;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR RIAGENDR AvgAlc*RIAGENDR;
contrast "OR - AvgAlc - RIAGENDR = 0" AvgAlc 5 AvgAlc*RIAGENDR 10 / est=exp;
run;
*males;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR RIAGENDR AvgAlc*RIAGENDR;
contrast "OR - AvgAlc - RIAGENDR = 0" AvgAlc 5 AvgAlc*RIAGENDR 5 / est=exp;
run;

*3c 4 vs 2;
proc logistic data=epi550.nhanes_htn;	*females;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR RIAGENDR AvgAlc*RIAGENDR;
contrast "OR - AvgAlc - RIAGENDR = 0" AvgAlc 2 AvgAlc*RIAGENDR 4 / est=exp;
run;
proc logistic data=epi550.nhanes_htn;	*males;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR RIAGENDR AvgAlc*RIAGENDR;
contrast "OR - AvgAlc - RIAGENDR = 0" AvgAlc 2 AvgAlc*RIAGENDR 2 / est=exp;
run;

*7; *no EMM;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR RIAGENDR ;
contrast "OR, AvgAlc=5" AvgAlc 5 / est=exp;
run;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5 RIDAGEYR;
contrast "OR, AvgAlc=5" AvgAlc 5 / est=exp;
run;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5 RIAGENDR;
contrast "OR, AvgAlc=5" AvgAlc 5 / est=exp;
run;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc RIDAGEYR RIAGENDR;
contrast "OR, AvgAlce=5" AvgAlc 5 / est=exp;
run;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc MealsOut5;
contrast "OR, AvgAlce=5" AvgAlc 5 / est=exp;
run;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc RIDAGEYR ;
contrast "OR, AvgAlce=5" AvgAlc 5 / est=exp;
run;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc  RIAGENDR;
contrast "OR, AvgAlce=5" AvgAlc 5 / est=exp;
run;
proc logistic data=epi550.nhanes_htn;
model HTN (event="1")= AvgAlc;
contrast "OR, AvgAlce=5" AvgAlc 5 / est=exp;
run;
