libname epi550 "H:\EPI550";
proc contents data=epi550.mammo_data;
run;
*score test for OLR (#1);
proc logistic data=epi550.mammo_data descending;
model MAMEXP = bse hist pb;
run;
*2;
*PLR:gold standard;
proc logistic data=epi550.mammo_data;
class pb;
model MAMEXP (ref='0') = bse hist pb / link=glogit;
run;
*OLR:gold standard;
proc logistic data=epi550.mammo_data descending;
model MAMEXP = bse hist pb;
run;
*3b;
*crude models;
	*PLR;
	proc logistic data=epi550.mammo_data;
	model MAMEXP (ref='0') = bse / link=glogit;
	run;
	*OLR;
	proc logistic data=epi550.mammo_data descending;
	model MAMEXP = bse;
	run;
*model with just hist (excluding pb);
	*PLR;
	proc logistic data=epi550.mammo_data;
	model MAMEXP (ref='0') = bse hist / link=glogit;
	run;
	*OLR;
	proc logistic data=epi550.mammo_data descending;
	model MAMEXP = bse hist;
	run;
*model with just pb (excluding hist);
	*PLR;
	proc logistic data=epi550.mammo_data;
	class pb;
	model MAMEXP (ref='0') = bse pb / link=glogit;
	run;
	*OLR;
	proc logistic data=epi550.mammo_data descending;
	model MAMEXP = bse pb;
	run;
*4;
*OLR with PB, not hist;
proc logistic data=epi550.mammo_data descending;
model MAMEXP = bse pb;
run;


