libname epi550 "H:\EPI550";
proc contents data=epi550.vets;
run;
*1 TX;
*log-log survival curves;
proc lifetest data=epi550.vets method=km plots=lls;
time survt*status(0);
strata tx;
run;
*goodness of fit;
proc phreg data=epi550.vets;
model survt*status(0)=tx;
assess ph / resample;
run;
*time-dependent covariates;
*g(t)=t;
proc phreg data=epi550.vets;
model survt*status(0)=tx tx_t;
tx_t=tx*survt;
run;
*g(t)=ln(t);
proc phreg data=epi550.vets;
model survt*status(0)=tx tx_lnt;
tx_lnt=tx*log(survt);
run;
*2 AGE;
*investigate age variable;
proc univariate data=epi550.vets;
var age;
run; *34-81 year olds, mean=58 median=62;
*categorize into 2 groups: 34-62 and >62;
data epi550.vets;
    set epi550.vets;
    if age <= 62 then age_cat = 1;
    else age_cat = 2;
run;
*log-log survival curves;
proc lifetest data=epi550.vets method=km plots=lls;
    time survt*status(0);
    strata age_cat;
run;
*categorize into 3 groups;
proc rank data=epi550.vets out=ranked_age groups=3;
var age; 
ranks tertile;
run;
proc means data=ranked_age;
    class tertile;
    var age;
run;	
*3 groups: 34-54, 55-64, 65-81;
data epi550.vets;
set epi550.vets;
if 34 <= age <=54 then age_cat=0;
else if 55 <= age <= 64 then age_cat = 1; 
else if age >= 65 then age_cat = 2; 
run;
*log-log survival curves;
proc lifetest data=epi550.vets method=km plots=lls;
    time survt*status(0);
    strata age_cat;
run;
*goodness of fit;
proc phreg data=epi550.vets;
model survt*status(0)=age;
assess ph / resample;
run;
*time-dependent covariates;
*g(t)=t;
proc phreg data=epi550.vets;
model survt*status(0)=age age_t;
age_t=age*survt;
run;
*g(t)=ln(t);
proc phreg data=epi550.vets;
model survt*status(0)=age age_lnt;
age_lnt=age*log(survt);
run;
*3 PRIORTX;
*log-log survival curves;
proc lifetest data=epi550.vets method=km plots=lls;
time survt*status(0);
strata priortx;
run;
*goodness of fit;
proc phreg data=epi550.vets;
model survt*status(0)=priortx;
assess ph / resample;
run;
*time-dependent covariates;
*g(t)=t;
proc phreg data=epi550.vets;
model survt*status(0)=priortx priortx_t;
priortx_t=priortx*survt;
run;
*g(t)=ln(t);
proc phreg data=epi550.vets;
model survt*status(0)=priortx priortx_lnt;
priortx_lnt=priortx*log(survt);
run;
*5;
*crude;
proc phreg data=epi550.vets;
model survt*status(0)=priortx/rl;
run;
*adjusted;
proc phreg data=epi550.vets;
model survt*status(0)=priortx age/rl;
run;
