libname epi550 "H:\EPI550";
proc contents data=epi550.vets;
run;
*3 method 1;
proc phreg data=epi550.vets;
model survt*status(0)=priortx age/rl;
by tx;
run;
*6 method 2;
proc phreg data=epi550.vets;
model survt*status(0)=priortx age priortx*tx age*tx/rl;
strata tx;
run;
*using contrast statemetns to get HR nd CIs;
proc phreg data=epi550.vets;
model survt*status(0)=priortx age priortx*tx age*tx/rl;
strata tx;
contrast "HR for standard therapy" priortx 1 priortx*tx 1 / estimate=exp;
contrast "HR for experimental therapy" priortx 1 priortx*tx 2 / estimate=exp; 
run;
*7 LRT;
*full model;
proc phreg data=epi550.vets;
model survt*status(0)=priortx age priortx*tx age*tx/rl;
strata tx;
run;
*reduced model;
proc phreg data=epi550.vets;
model survt*status(0)=priortx age/rl;
strata tx;
run;
data LRT;
p=1-probchi(838.770-837.092, 2);
run;
proc print data=LRT;
run;
