libname lab2 "S:\course\BIOS500\Binongo\2023_Lab\Datasets";
proc contents data=lab2.heart;
run;
proc univariate data=lab2.heart;
var systolic;
class sex;
run;
proc univariate data=lab2.heart;
var diastolic;
run;
proc univariate data=lab2.heart;
var weight;
class sex;
run;
proc univariate data=lab2.heart;
var AgeCHDdiag;
run;
data work.heart2;
set lab2.heart;
bmi=weight*703/height**2;
run;
proc univariate data=work.heart2;
var bmi;
run;

proc univariate data=lab2.heart;
var cholesterol;
class weight_status;
run;
proc univariate data=lab2.heart;
var cholesterol;
run;
proc means data=lab2.heart nmiss;
var cholesterol;
run;
PROC SGPLOT DATA=lab2.HEART;
HBOX DIASTOLIC / CATEGORY=STATUS;
            RUN;
PROC SGPLOT DATA=lab2.HEART;
HBOX DIASTOLIC / CATEGORY=STATUS;
XAXIS LABEL="Diastolic BP, mmHg";
YAXIS LABEL="Status";
TITLE "Sophie Bustamante";
FOOTNOTE "Distribution of Diastolic Blood Pressure by Status";
RUN;      		*works^;
 PROC UNIVARIATE DATA=lab2.HEART;
VAR DIASTOLIC;
HISTOGRAM DIASTOLIC/NORMAL;
CLASS STATUS;
FOOTNOTE "Distribution of Diastolic Blood Pressure by Status";
Run;

PROC SGPLOT DATA=lab2.HEART;
HBOX DIASTOLIC / CATEGORY=STATUS;
            RUN;

PROC UNIVARIATE DATA=lab2.HEART;
VAR DIASTOLIC;
HISTOGRAM DIASTOLIC/NORMAL;
CLASS STATUS;
FOOTNOTE "Distribution of Diastolic Blood Pressure by Status";
Run;

PROC UNIVARIATE DATA=lab2.HEART;
VAR DIASTOLIC;
HISTOGRAM DIASTOLIC/NORMAL;
CLASS STATUS;
INSET MEAN STD / HEADER= 'Sophie';
FOOTNOTE "Distribution of Diastolic Blood Pressure by Status";
Run;
