*HW;
libname lab7 'S:\course\BIOS500\Binongo\2023_Lab\Datasets';
proc contents data=lab7.exposure;
run;
proc means data=lab7.exposure;
var chol;
run;
*3;
PROC TTEST DATA=lab7.exposure H0=180 ALPHA=0.05;
	VAR chol;
RUN;
*5;
proc print data=lab7.exposure;
var sex;
run;
proc means data=lab7.exposure;
var bmi;
where sex="M";
run;
proc means data=lab7.exposure;
var bmi;
where sex="F";
run;
PROC TTEST DATA=lab7.exposure ALPHA=0.05;
	VAR bmi;
	CLASS sex;
RUN;
*Pr > |t| = <.0001-->reject H0 (reject that there is no difference-->there is a stat sig diference);
*8;
PROC TTEST DATA=lab7.exposure ALPHA=0.05;
	PAIRED fev_6months*fev;	 
RUN;
