
*2c;
data q2c;
prob_le5= cdf ("bino", 5, 0.008, 500);
run;
proc print data=q2c;
run;
*2d;
data q2d;
prob_ge3_le5= cdf("bino", 5, 0.008, 500) - cdf("bino", 2, 0.008, 500);
run;
proc print data=q2d;
run;

*3a;
data baby;
prob_lt2200= cdf("norm", 2200, 3240, 495);
run;
proc print data=baby;
run;
*3b;
data baby;
lowest2=quantile ("norm", 0.02, 3240, 495);
run;
proc print data=baby;
run;
*3c;
data baby;
prob_lt3700_gt3300=cdf ("norm", 6.5051) - cdf ("norm", 0.85);
run;
proc print data=baby;
run;
libname midterm "H:\BIOS500";
*4a;
proc contents data=midterm.nist;
run;
proc freq data=midterm.nist;
tables gender;
run;
proc univariate data=midterm.nist;
var age;
run;
proc freq data=midterm.nist;
tables race;
run;
proc univariate data=midterm.nist;
var c1r;
run;
proc univariate data=midterm.nist;
where gender="FEMALE";
var age;
run;
proc univariate data=midterm.nist;
where gender="MALE";
var age;
run;
proc freq data=midterm.nist;
tables gender*race;
run;
proc univariate data=midterm.nist;
where gender="FEMALE";
var c1r;
run;
proc univariate data=midterm.nist;
where gender="MALE";
var c1r;
run;
*4b; 
proc freq data=midterm.nist;
tables povsta*cpx_had;
run;
*4c;
data q4;
set midterm.nist;
if race="	" or povsta="	" or gender="	" then x="	";
run; 
*4ci;
proc freq data=q4;
tables race*povsta;
run;
*4cii;
proc freq data=q4;
where gender="FEMALE";
tables race*povsta;
run;
*4ciii & iv;
proc freq data=q4;
tables race*povsta;
run;
*4cvi;
proc freq data=q4;
where gender="FEMALE" and race ^= "BLACK ONLY";
tables povsta;
run;
proc freq data=q4;
tables gender*race;
run;
*4cvii;
proc freq data=q4;
where race NE "BLACK ONLY";
tables povsta*gender;
run;
proc freq data=q4;
tables race;
run;
